[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[functions."office-push-worker"]
  schedule = "* * * * *"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
